from pathlib import Path

path = Path("shuo/agent.py")
text = path.read_text(encoding="utf-8-sig")
old = '''        self._response.append(token)\n        if self._phrase_buffer is None:\n            self._tts_text_chunks += 1\n            await self._tts.send(token)\n        else:\n            for chunk in self._phrase_buffer.feed(token):\n                self._tts_text_chunks += 1\n                await self._tts.send(chunk)\n\n    async def _on_llm_done(self) -> None:\n        """LLM finished -> flush any bounded phrase fragment, then end TTS."""\n        if not self._active or not self._tts:\n            return\n        self._tracer.end(self._turn, "llm")\n        if self._phrase_buffer is not None:\n            pending = self._phrase_buffer.flush()\n            if pending:\n                self._tts_text_chunks += 1\n                await self._tts.send(pending)\n            log.info(\n                f"TTS text batching turn={self._turn} chunks={self._tts_text_chunks} "\n                f"max_chars={self._tts_phrase_chars}"\n            )\n        await self._tts.flush()'''
new = '''        self._response.append(token)\n        # A few legacy tests intentionally construct Agent via __new__ to isolate\n        # token accumulation. Treat absent Phase-4D fields exactly like the\n        # default-off path so constructor-bypass tests and compatible embeddings\n        # retain their previous behavior.\n        phrase_buffer = getattr(self, "_phrase_buffer", None)\n        if phrase_buffer is None:\n            self._tts_text_chunks = getattr(self, "_tts_text_chunks", 0) + 1\n            await self._tts.send(token)\n        else:\n            for chunk in phrase_buffer.feed(token):\n                self._tts_text_chunks = getattr(self, "_tts_text_chunks", 0) + 1\n                await self._tts.send(chunk)\n\n    async def _on_llm_done(self) -> None:\n        """LLM finished -> flush any bounded phrase fragment, then end TTS."""\n        if not self._active or not self._tts:\n            return\n        if self._tracer is not None:\n            self._tracer.end(self._turn, "llm")\n        phrase_buffer = getattr(self, "_phrase_buffer", None)\n        if phrase_buffer is not None:\n            pending = phrase_buffer.flush()\n            if pending:\n                self._tts_text_chunks = getattr(self, "_tts_text_chunks", 0) + 1\n                await self._tts.send(pending)\n            log.info(\n                f"TTS text batching turn={self._turn} "\n                f"chunks={getattr(self, '_tts_text_chunks', 0)} "\n                f"max_chars={getattr(self, '_tts_phrase_chars', None)}"\n            )\n        await self._tts.flush()'''
if text.count(old) != 1:
    raise SystemExit(f"expected one generated Agent callback marker, found {text.count(old)}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("Phase 4D Agent compatibility fix applied")
